[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
crowdfunding = "FSdwWj1XYtrgf5xyNq7exDXzNGBUZ7ZSuG2zwoxRprwR"

[programs.devnet]
crowdfunding = "FSdwWj1XYtrgf5xyNq7exDXzNGBUZ7ZSuG2zwoxRprwR"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"

[hooks]
