[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
crowdfunding = "F3k9VhRhE9JwkgRNryjkzu7CL3z8epdLc3hHxe2Bg5gu"

[programs.devnet]
crowdfunding = "F3k9VhRhE9JwkgRNryjkzu7CL3z8epdLc3hHxe2Bg5gu"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[hooks]
